SELECT datname FROM pg_database WHERE datbda IN (SELECT usesysid FROM pg_user WHERE usename= 'nom de connexion');
SELECT cli_nom FROM client;
SELECT * FROM client;
SELECT DISTINCT (cde_commande) FROM commande;
SELECT cli_prenom FROM client WHERE cli_prenom LIKE 'sophie';
SELECT art_id, cde_qte FROM commande WHERE cli_id=1;
SELECT upper (cli_nom) FROM client;
SELECT cli_nom FROM client WHERE upper(cli_nom)='%';
SELECT cli_nom FROM client WHERE LENGTH(cli_nom) BETWEEN 1 AND 5;
SELECT cli_nom FROM client WHERE cli_nom LIKE 't_l%';
SELECT cli_id, art_id, cde_date, cde_date + integer '15' AS date_paiment FROM commande;
SELECT cli_nom, cli_prenom, cli_datent FROM client ORDER BY cli_datent ASC;
SELECT cli_nom, cli_prenom CURRENT_TIMESTAMP-cli_datent FROM client ORDER BY cli_datent ASC;
SELECT CURRENT_TIMESTAMP;
ALTER TABLE commande ALTER COLUMN cde_qte TYPE integer USING (cde_qte::integer);
SELECT MAX(cde_qte) AS cde_qte_max FROM commande;
SELECT SUM (cde_qte) AS cde_qte_total_client1 FROM commande WHERE cli_id=1;
SELECT ROUND(AVG(cde_qte), 2) AS cde_qte_moeyenne_client2 FROM commande WHERE cli_id=2;
SELECT cli_nom FROM client ORDER BY cli_nom ASC;
SELECT * FROM article ORDER BY art_prix DESC;
SELECT cli_id, cli_nom, cli_prenom FROm client ORDER BY cli_nom ASC;